[build]
  functions = "netlify/functions"
  
[build.environment]
  NODE_ENV = "production"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[functions."analysis"]
  timeout = 10
