services:
  # Backend Service
  - type: web
    name: real-estate-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_API_KEY
        value: AIzaSyB6bgowsUoIjSuXrild8BZ263fc9z-wwNo
      - key: JWT_SECRET
        value: render_jwt_secret_2025_production_very_long_key
      - key: FRONTEND_URL
        value: https://enchanting-treacle-a8c0cf.netlify.app
    healthCheckPath: /health

  # Frontend Service  
  - type: web
    name: real-estate-analyzer-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://real-estate-analyzer-backend.onrender.com 